import Link from 'next/link'; import { notFound } from 'next/navigation';
const essays:Record<string,{title:string;subtitle:string;lead:string;sections:[string,string][]}> = {
'zeitformen':{title:'Zeitformen der Kontrakomologie',subtitle:'Ein Systemtext',lead:'Zeit ist nicht das, worin Musik stattfindet. Zeit ist das, was Musik tut.',sections:[
['Warum mehrere Zeitformen','Kontrakomologie beginnt mit einer einfachen Beobachtung: Bach und Davis erzeugen beim Hören grundlegend verschiedene Zeitstrukturen. Das liegt nicht nur an Tempo, Epoche oder Besetzung. Bach macht Zeit gleichzeitig. Davis macht Zeit offen. Coltrane macht Zeit gerichtet. Die Begriffe entstehen aus dem Hören der Werke – nicht aus einer Theorie, unter die sie anschließend eingeordnet werden.'],
['Strukturelle Gleichzeitigkeit','Bach, Die Kunst der Fuge: Mehrere vollständige Linien verlaufen gleichzeitig, jede nach eigener Logik, keine erklärt der anderen, was sie zu tun hat. Ordnung entsteht durch Eigenständigkeit. Hörweise: erst einer Stimme folgen, dann allen gleichzeitig, dann dem, was keine von ihnen allein enthält.'],
['Retrospektive Zeitrichtung','Beethoven und Chopin: Das Werk läuft vorwärts; Bedeutung entsteht zugleich rückwärts. Der Schluss lädt den Anfang semantisch um. Ein zweites Hören verändert die erste Erfahrung.'],
['Emergente Offenzeit','Miles Davis, Kind of Blue: Zeit entsteht im Spielen. Modale Felder schwächen das vorgeschriebene harmonische Ziel; jeder Ton verändert im Moment des Erklingens, was als Nächstes möglich ist.'],
['Gerichtete Transformation','John Coltrane, A Love Supreme: Zeit hat ein Ziel und kommt an. Vier Zustände werden vorwärts durchlaufen und rückwirkend als zusammengehörige Einheit erkannt.'],
['Resonanzzeit','Bill Evans: Zeit verdichtet sich im Nachklang. Ein einzelner Ton kann mehr Zeit tragen als eine Passage; Pausen sind keine Lücken, sondern aktive Form.'],
['Pulsflusszeit','Steve Reich: Bewegung als Zustand statt als Weg. Muster verändern sich fortwährend, ohne auf eine funktionale Auflösung zuzusteuern.'],
['Stehende Innenzeit','Madonna, Frozen: Die Innenzeit steht, während die Außenzeit weiterläuft. Gedehnte Klangschichten, Stimme und metrischer Puls tragen verschiedene Zeitqualitäten gleichzeitig.'],
['Aufrecht erhaltene Gegenwart','Evanescence, My Immortal: Eine Gegenwart wird gehalten – nicht bloß als Erstarrung, sondern als Entscheidung, in einer Bindung zeitlich zu verbleiben.'],
['Simultane Gegensätze','The Cars, Drive: Zwei Wahrheiten bleiben gleichzeitig bestehen, ohne sich aufzulösen. Das kreisende harmonische Feld hält eine Gegenwart, die sich nicht entscheidet.'],
['Ein offenes System','Die Zeitformen sind keine vollständige Klassifikation. Sie beschreiben Formen, die sich in konkreten Werken gezeigt haben. Andere Werke können andere Formen sichtbar machen. Kontrakomologie klassifiziert nicht zuerst – sie hört und beschreibt.']]},
'komponieren':{title:'Kontrakomologisches Komponieren',subtitle:'Prinzipien einer Praxis',lead:'Nicht: Wie klingt es? Sondern: Was tut es mit der Zeit?',sections:[
['Vom Analysieren zum Komponieren','Wer beschreiben kann, warum eine musikalische Entscheidung eine bestimmte Zeitwirkung erzeugt, gewinnt daraus auch eine Kompositionsfrage. Die folgenden Prinzipien sind keine Vorschriften, sondern aus dem Hören gewonnene Arbeitsweisen.'],
['Tonmaterial: Teleologiefreiheit','Die erste Frage lautet nicht, was schön klingt, sondern wohin das Material drängt. Leitton, Dominante, Modalität, Pentatonik oder Drone sind damit nicht bloß Stilentscheidungen, sondern Entscheidungen über Zeit und Erwartung.'],
['Zeitbehandlung: Dichte statt Tempo','Zeitqualität hängt nicht nur vom Tempo ab. Entscheidend sind Phrasierung, Nachklang, Ereignisdichte und der Raum zwischen Ereignissen. Eine Pause kann selbst musikalische Zeit tragen.'],
['Formlogik: Rückwirkung','Ein Schluss kann das Frühere neu lesen. Eine Form wird bidirektional, wenn das zweite Hören die erste Erfahrung nicht einfach wiederholt, sondern verändert.'],
['Mehrschichtigkeit','Mehrere Ebenen können gleichzeitig eigenständig bleiben: melodische Linien, Sprachen, Klangschichten oder Zeitqualitäten. Koexistenz ersetzt die automatische Hierarchie von Hauptstimme und Begleitung.'],
['Schlussgeste','Ein Ende muss nicht alle Spannungen auflösen. Der letzte Ton kann eine Form im Hörer weiterarbeiten lassen. Entscheidend ist, was bleibt, nachdem die Musik aufgehört hat.'],
['Keine Stilistik','Kontrakomologisches Komponieren schreibt weder Pentatonik noch Drone noch offene Form vor. Die Mittel folgen der Zeitfrage des jeweiligen Werks. Ein Verfahren ist nur dann relevant, wenn seine Wirkung tatsächlich hörbar wird.']]},
'lesen':{title:'Kontrakomologisch lesen',subtitle:'Prinzipien einer Praxis',lead:'Ein Werk erzeugt Zeit. Das gilt für eine Fuge. Es gilt auch für einen Satz.',sections:[
['Dieselbe Frage, anderes Material','Die Kontrakomologie entstand aus dem Hören, doch ihre Fragen lassen sich auch an Sätze, Figuren und Romanstrukturen stellen. Ein Roman beschreibt Zeit nicht nur – er erzeugt beim Lesen eine bestimmte Zeiterfahrung.'],
['Stimmen im Text','Gefragt wird, wie viele unabhängige Zeitebenen und Bedeutungsstimmen ein Text gleichzeitig trägt. Eine Figur kann in Handlung und Erinnerung zugleich leben; ein Erzähler kann beobachten und zugleich nicht verstehen.'],
['Bidirektionales Lesen','Nach dem Ende besitzt der Leser mehr Information als am Anfang. Ein Werk mit bidirektionaler Zeitarchitektur lässt sich deshalb beim zweiten Lesen anders erfahren: Das Ende war im Anfang bereits wirksam, wird aber erst später erkennbar.'],
['Die Pause im Prosatext','Nicht-Gesagtes, abgebrochene Sätze und bewusst offene Szenen können wie musikalische Pausen funktionieren: nicht als Leerstelle, sondern als Form von Anwesenheit und Nachwirkung.'],
['Zeitform erkennen','Die Frage lautet nicht nur, was geschieht, sondern welche Art von Zeit der Text erzeugt: gerichtete, gleichzeitige, stehende, offene oder andere Zeit.'],
['Nalgae – ein Beispiel','Hanas Gegenwart trägt mehrere Zeitschichten gleichzeitig. Herzschlag, generationenübergreifender Drone, Flimmern und die Linie der Frauen funktionieren als eigenständige Stimmen. Spätere Kapitel verändern rückwirkend, was im ersten bereits wahrnehmbar war.']]},
};
export default async function Page({params}:{params:Promise<{locale:string;slug:string}>}){const {locale,slug}=await params;if(locale!=='de'||!essays[slug])notFound();const e=essays[slug];return <main className="shell"><header className="topbar"><Link className="brand" href="/de">Contracomology</Link><nav className="nav"><Link href="/de/documents">Publikationen</Link><Link href="/de/kg">Begriffe</Link></nav></header><article className="fulltext"><p className="eyebrow">Grundlagen</p><h1>{e.title}</h1><p className="fulltext-subtitle">{e.subtitle}</p><p className="fulltext-author">Thomas Peter Küper</p><blockquote>{e.lead}</blockquote>{e.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<p className="back-link"><Link href="/de/documents">← Zurück zu den Publikationen</Link></p></article><footer className="subpage-footer"><div className="footer-links"><Link href="/de/legal/imprint">Impressum</Link><Link href="/de/legal/privacy">Datenschutz</Link><Link href="/de/legal/terms">Nutzungsbedingungen</Link><Link href="/de/legal/ai-transparency">KI-Transparenz</Link></div><p>© 2026 Thomas Peter Küper</p></footer></main>}